### ISSUE TITLE
Screenshots of the app in README

### ISSUE THREAD

**Issue by chalda** [Denperidge/community-pinboard#19]
This looks awesome for both my whatsapp community and local community but its a decent amount of work to get it all setup to just get it running to actually see what it looks like and get an idea of how it works 

(as in not a aptget/brew install and off to the races :P )

**Comment by Denperidge** [comment]
Totally fair, I'm on it! Currently still rudimentary and until the edit page is properly fixed, not yet ready for production. But I'm happy with the interest, and will add some screenshots!

**Comment by Denperidge** [comment]
@chalda Added the screenshot! Let me know if the screenshot is decent enough to give you an idea

**Comment by Denperidge** [comment]
Closing the issue for now due to some screenshots being added, feel free to re-open in case there's an issue with them!
